#8 [feat] 고객이 자신의 프로필 관리(설정,조회)기능 구현완료
i-kemen/tomato-market pull request #35
Opened 2023-01-18 12:04 UTC by ShahBle

2023-01-18 12:05 UTC, ljwon1203 approved these changes

2023-01-18 12:28 UTC, mitoconcrete requested changes
변경사항 구현 후 재 요청부탁드려요!

2023-01-18 12:28 UTC, mitoconcrete commented on src/main/java/com/team8/shop/tomatomarket/dto/GetSellerRespDto.java
> +//    private final Long id;
원상복구 부탁드려요

2023-01-18 12:28 UTC, mitoconcrete commented on src/main/java/com/team8/shop/tomatomarket/repository/UserRepository.java
> +import java.util.List;
사용되지 않는 import 문은 제거해주세요

2023-01-18 12:28 UTC, mitoconcrete commented on src/main/java/com/team8/shop/tomatomarket/controller/UserController.java
> +        if(userDetails.getUser().getId().equals(userId)){
현재 User 엔티티에 있는 isValidId를 UserDetailsImpl로 옮겨서 검증을 구현해보세요!

2023-01-18 12:28 UTC, mitoconcrete commented on src/main/java/com/team8/shop/tomatomarket/dto/UserMyProfileDto.java
> +
controller에서 인자로 받은 userId 와 nickname을 담아서 넘기셔도 좋습니다!

2023-01-18 12:28 UTC, mitoconcrete commented on src/main/java/com/team8/shop/tomatomarket/service/UserServiceImpl.java
> +        if(user.isRole() || user.isValidUsername(user.getUsername()))
role은 시큐리티에서 검증하고, username검증은 굳이해주실 필요없어서, Entitiy에서 제거해주시고, 그에 따라 이 로직도 삭제해주시면 됩니다!

2023-01-18 12:28 UTC, mitoconcrete commented on src/main/java/com/team8/shop/tomatomarket/service/UserServiceImpl.java
> +        String username = userMyProfileDto.getUsername();
dto에 username 이 아닌 @PathVariable로 넘겨받은 Id 를 전달해줌에 따라, 이곳에 Id를 넣어주시고, 
findById를 이용해 user객체를 가져와주세요!

2023-01-19 06:40 UTC, mitoconcrete requested changes

2023-01-19 06:40 UTC, mitoconcrete commented on src/main/java/com/team8/shop/tomatomarket/service/UserServiceImpl.java
>              user.updateNickName(nickname);
업데이트 하신 엔티티는 repository 에 save를 해주셔야합니다!

2023-01-19 06:54 UTC, mitoconcrete approved these changes

2023-01-19 06:57 UTC, merged