Feature/#12
i-kemen/tomato-market pull request #41
Opened 2023-01-19 08:11 UTC by ahnhadi

2023-01-19 08:23 UTC, ljwon1203 approved these changes

2023-01-19 10:11 UTC, mitoconcrete requested changes

2023-01-19 10:11 UTC, mitoconcrete commented on src/main/java/com/team8/shop/tomatomarket/dto/ProductRequestDto.java
> +public class ProductRequestDto {
해당 dto는 request를 전달받는 dto입니다.
jackson이라는 라이브러리가 이안에 요청으로 보낸 데이터를 넣기위해서는 기본생성자가 필요합니다.
따라서, @NoArgsConstructor 를 붙혀주시고, 20번째 라인에 생성된 생성자는 responseDto를 따로만들고 그 안에 넣어주시는 것이 좋습니다.

2023-01-19 10:11 UTC, mitoconcrete commented on src/main/java/com/team8/shop/tomatomarket/dto/ProductRequestDto.java
> +    private ProductCategory productCategory;
클라이언트에서 보낼때 카테고리 이름 혹은 id 를 보낼 것 같습니다.
하지만, 이건 아예 로직을 변경해야할 것 같아서 우선 두셔도 좋을 것 같습니다.

2023-01-19 10:19 UTC, ShahBle approved these changes

2023-01-20 02:11 UTC, mitoconcrete requested changes

2023-01-20 02:11 UTC, mitoconcrete commented on src/main/java/com/team8/shop/tomatomarket/controller/SellerController.java
> +        Long checkSellerUserId = sellerService.getSeller(sellerId).getUser().getId();
sellerServiceImpl 이 되어야 할거에용. 바꾸시는김에 이 페이지에 모든서비스명을 sellerServiceImpl 으로 변경부탁드려요!

2023-01-20 02:14 UTC, mitoconcrete approved these changes

2023-01-20 02:15 UTC, merged