#20[feat] (고객, 판매자, 관리자) 예외처리 API
i-kemen/tomato-market pull request #50
Opened 2023-01-21 03:34 UTC by ljwon1203

2023-01-21 04:04 UTC, mitoconcrete requested changes

2023-01-21 04:04 UTC, mitoconcrete commented on src/main/java/com/team8/shop/tomatomarket/exception/RestApiExceptionHandler.java
> +        RestApiException restApiException = new RestApiException();
13~20 번째 줄을 하나로 합칠수있습니다!
또한 현재 우리서비스는 ResponseEntity를 사용하고 있지않으니, 그냥 DTO만 뱉는형태로 비꿔주시면 감사드리겠습니다!

2023-01-21 05:32 UTC, mitoconcrete requested changes

2023-01-21 05:32 UTC, mitoconcrete commented on src/main/java/com/team8/shop/tomatomarket/exception/RestApiException.java
> +@AllArgsConstructor
이 안의 멤버변수들은 한번 할당되면 그 이후로 변하지 않는 값들입니다!
이렇게 작성하셔도 동작에 큰 무리는 없지만, 멤버변수 final로 정의하시고, 그에 맞는 생성자를 생성해주는 어노테이션을 사용해보셔도 좋을것같아요!

2023-01-22 00:21 UTC, mitoconcrete approved these changes

2023-01-23 12:28 UTC, ahnhadi approved these changes

2023-01-23 12:29 UTC, merged